import 'package:flutter/material.dart';
import 'payment_webview.dart';

/// A ready-to-use payment button that opens the BjPay checkout widget.
///
/// Place [Bjpay] anywhere in your widget tree. Tapping it pushes a screen
/// that loads the BjPay payment widget for the given [totalamount] and
/// [token]; [onSuccess] or [onFailure] is called with the payment details
/// once the transaction completes.
class Bjpay extends StatelessWidget {
  /// The amount to charge, in the currency configured for [token].
  ///
  /// Must be finite and strictly positive, and should match the amount of
  /// the transaction created on your backend.
  final double totalamount;

  /// The payment token (JWT) generated by your backend for this transaction.
  ///
  /// This SDK does not generate the token itself.
  final String token;

  /// Called with the payment details when the transaction succeeds.
  final void Function(Map<String, dynamic> data)? onSuccess;

  /// Called with the payment details when the transaction fails.
  ///
  /// Not called if the user simply closes the payment widget without
  /// completing the transaction.
  final void Function(Map<String, dynamic> data)? onFailure;

  /// Creates a BjPay payment button for [totalamount] using [token].
  Bjpay({
    super.key,
    required this.totalamount,
    required this.token,
    this.onSuccess,
    this.onFailure,
  }) : assert(
         totalamount.isFinite && totalamount > 0,
         'totalamount must be a finite, positive number',
       );

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      style: ElevatedButton.styleFrom(
        backgroundColor: Colors.green,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
      ),
      onPressed: () {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => PaymentWebView(
              totalamount: totalamount,
              token: token,
              onSuccess: onSuccess,
              onFailure: onFailure,
            ),
          ),
        );
      },
      child: const Text("Payer avec BjPay"),
    );
  }
}
